CREATE TABLE EMPLOYEE(
EMP_ID NUMBER PRIMARY KEY,
NAME_FIRST VARCHAR2 (50),
NAME_LAST VARCHAR2 (50),
EMAIL VARCHAR2 (50),
USER_NAME VARCHAR2 (50),
PASS_WORD VARCHAR2 (50),
AVAIL_REIM NUMBER);




INSERT INTO EMPLOYEE VALUES (1, 'Zach', 'Patton', 'zacharypatton1991@gmail.com', 'ZP', 'pass', 1000);

SELECT * FROM EMPLOYEE WHERE EMP_ID = 1;